### ISSUE TITLE
Scatter Chart - kmeans hirarchical function in n Cluster

### ISSUE THREAD

**Issue by AndreasWidmer** [w11k/superset-chart-plugins#2]
Als User möchte ich ein Clustering im Scatter Chart angezeigt bekommen.

Geschätzter Aufwand: 2-4 Tage

**Comment by kaihenzler** [comment]
## Control Panel
### Only Visible in Raw Records Mode
![Bildschirmfoto 2021-12-07 um 07 39 19](https://user-images.githubusercontent.com/4253453/144981726-de685b5c-17dc-4671-b845-975eab0b8eaa.png)

### No Clustering Selected
![Bildschirmfoto 2021-12-07 um 07 58 25](https://user-images.githubusercontent.com/4253453/144981685-b685342b-e420-422d-b72a-27032a2ddeaa.png)

### Clustering Activated (Select Type)
![Bildschirmfoto 2021-12-07 um 07 58 03](https://user-images.githubusercontent.com/4253453/144982017-277e901b-485e-4b71-9342-2cbbca0aae3b.png)

### Clustering by hierarchical kMeans
![Bildschirmfoto 2021-12-07 um 08 10 39](https://user-images.githubusercontent.com/4253453/144983054-ae7b5c3f-c332-4369-916d-5d96a05ca1ba.png)

Editable Select Fields is displayed to select the number of clusters we want to build

## Display Logic
- we use this library for clustering: https://github.com/ecomfe/echarts-stat#clustering
- a very early prototype is in branch `ecstat-clustering-prototype`. We can see how to import the ecStat library in this branch and also how to setup the transform. 
- In my understanding we can not have any other transforms when using this type of clustering, we only supply the sourceDataset, one series and a clustering transform
